### ISSUE TITLE
With valid login id & password unable to log in the practice page

### ISSUE THREAD

**Issue by rajesh1994** [letskodeit/selenium-python-novice-ninja-files#1]
URL : https://sso.teachable.com/secure/42299/identity/login/password

Login ID : test@email.com

Password : abcabc

**Comment by letskodeit** [comment]
You are trying the old URL.

Please try this:
https://courses.letskodeit.com/

Thanks
Anil

**Comment by rajesh1994** [comment]
Thanks for your reply.

It means a lot.
